### PR TITLE
Revert "Technical report"

### PR DESCRIPTION
**Pull request by ngeiswei**
@Eman22S, I've merged your PR https://github.com/singnet/ai-dsl/pull/35 too fast, didn't realize it was incomplete. I'm reverting it now because it doesn't compile yet.

### CODE REVIEW

**Comment by ngeiswei** [comment]
To compile/test your report you must run `./render.sh` under the `doc/technical-reports/2021-05` folder.

**Comment by Eman22S** [comment]
Yes, its not complete yet. I am writing the remaining 2 sections locally and have not pushed it yet. Btw how do you write your idris code ? I tried copying your syntax `\begin{minted}[mathescape]{idris}` but not luck with me. I am writing on Overleaf btw.

**Comment by Eman22S** [comment]
Yes, its not complete yet. I am writing the remaining 2 sections locally and have not pushed it yet. Btw how do you write your idris code ? I tried copying your syntax `\begin{minted}[mathescape]{idris}` but not luck with me. I am writing on Overleaf btw.

**Comment by Eman22S** [comment]
Yes, its not complete yet. I am writing the remaining 2 sections locally and have not pushed it yet. Btw how do you write your idris code ? I tried copying your syntax `\begin{minted}[mathescape]{idris}` but not luck with me. I am writing on Overleaf btw.

**Comment by ngeiswei** [comment]
> Btw how do you write your idris code?

You need to install the texlive-minted package, but I don't know how to do that in overleaf.  You should be able to edit and compile it locally.  What is your distro?

**Comment by Eman22S** [comment]
Manjaro. I am installing the package now

**Comment by Eman22S** [comment]
I came across this error message when running `./render.sh` command bibtex not found command pdflatex not found what packages I need to install to get them?

**Comment by ngeiswei** [comment]
Yeah, on Manjaro you should be able to find everything you need in the official repositories, called texlive-core or something.

**Comment by Eman22S** [comment]
I managed to install it thanks.

**Comment by Eman22S** [comment]
Why do I get this error message ? when I run `./render.sh`

`
! Undefined control sequence.
\PYG #1#2->\FV@PYG 
`

**Pull request merged**
